name: test

on:
  push:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: run build
        run: npm run build
      - name: run tests
        run: npm run test
